//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeSandinoFinances.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancesChallengeDBEntities : DbContext
    {
        public FinancesChallengeDBEntities()
            : base("name=FinancesChallengeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expense_Detail> Expense_Detail { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Home_Expense_Detail> Home_Expense_Detail { get; set; }
        public virtual DbSet<Home_Expenses> Home_Expenses { get; set; }
    }
}
