//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeSandinoFinances.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Expenses
    {
        public int ID_Home_Expense { get; set; }
        public string Description_Home_Expense { get; set; }
    }
}
